name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file compose/local/core.Dockerfile --build-arg MYSQL_SERVER=10.46.0.160:3307 --tag fastapi-docker:$(date +%s) .
